---
- name: Generate multissh configration file path
  ansible.builtin.set_fact:
    configfile: '/etc/ssh/multissh/{{ instance }}_sshd_config'
    keyfile: '/etc/ssh/multissh/{{ instance }}_hostkey'

- name: Install SSH server
  ansible.builtin.apt:
    name:
      - openssh-server
    state: latest

- name: Create multissh configuration directory
  ansible.builtin.file:
    path: /etc/ssh/multissh
    state: directory
    mode: "0750"
    owner: root
    group: root

- name: Install multissh service file
  ansible.builtin.copy:
    src: multissh@.service
    dest: /etc/systemd/system/multissh@.service
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd

- name: Install multissh host key for {{ instance }}
  ansible.builtin.file:
    content: '{{ hostkey }}'
    dest: '{{ keyfile }}'
    mode: "0640"
    owner: root
    group: root
  notify:
    - Reload multissh instance

- name: Install multissh configuration for {{ instance }}
  ansible.builtin.template:
    src: sshd_config.j2
    dest: '{{ configfile }}'
    mode: '0640'
    owner: root
    group: root
  notify:
    - Reload multissh instance

- name: Enable multissh instance {{ instance }}
  ansible.builtin.systemd:
    name: 'multissh@{{ instance }}.service'
    state: started
    enabled: true
    daemon_reload: true

...
