---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload multissh instance
  ansible.builtin.systemd:
    name: 'multissh@{{ instance }}.service'
    state: reloaded

- name: Restart multissh instance
  ansible.builtin.systemd:
    name: 'multissh@{{ instance }}.service'
    state: restarted
...
